/*
 * Task Management API
 * A specialized API for managing organizational projects and their underlying tasks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Project;
import org.openapitools.client.model.ProjectInput;
import org.openapitools.client.model.Task;
import org.openapitools.client.model.TaskInput;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Create a new project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProjectTest() throws ApiException {
        ProjectInput projectInput = null;
        api.createProject(projectInput);
        // TODO: test validations
    }

    /**
     * Add a task to a project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTaskTest() throws ApiException {
        UUID projectId = null;
        TaskInput taskInput = null;
        api.createTask(projectId, taskInput);
        // TODO: test validations
    }

    /**
     * Get tasks for a specific project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProjectTasksTest() throws ApiException {
        UUID projectId = null;
        List<Task> response = api.getProjectTasks(projectId);
        // TODO: test validations
    }

    /**
     * List all projects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProjectsTest() throws ApiException {
        List<Project> response = api.getProjects();
        // TODO: test validations
    }

}
